version: 2

jobs:
  "Build - Dom Structure extension":
    docker:
      # Image built from the Dockerfile in the current repository
      - image: xebiafrance/contentful-extensions-build-container:v1
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - dom-structure/v1-npm-deps-{{ checksum "dom-structure/package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - dom-structure/v1-npm-deps-
      - run:
          name: Build React app
          command: |
            cd dom-structure/
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dom-structure/build
            - dom-structure/serverless.yml
      - save_cache:
          key: dom-structure/v1-npm-deps-{{ checksum "dom-structure/package-lock.json" }}
          paths:
            - "dom-structure/.node_modules"

  "Package Serverless - Dom Structure extension":
    docker:
      # Image built from the Dockerfile in the current repository
      - image: xebiafrance/contentful-extensions-build-container:v1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Create Serverless packages
          command: |
            cd dom-structure/
            serverless package -p package-prod -s prod
      - persist_to_workspace:
          root: .
          paths:
            - dom-structure/build
            - dom-structure/package-prod
            - dom-structure/serverless.yml

  "Deploy - Dom Structure extension":
    docker:
      # Image built from the Dockerfile in the current repository
      - image: xebiafrance/contentful-extensions-build-container:v1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to AWS S3
          command: |
            cd dom-structure/
            serverless deploy --force -p package-prod -s prod

workflows:
  version: 2
  full:
    jobs:
      - "Build - Dom Structure extension"
      - "Package Serverless - Dom Structure extension":
          requires:
            - "Build - Dom Structure extension"
      - "Deploy - Dom Structure extension":
          context: "Contentful Extensions - AWS Deployment"
          requires:
            - "Package Serverless - Dom Structure extension"
